on: push
name: Test on push
jobs:
  transition:
    name: update transition for defect DF001268
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to aqua saas instance
        id: login
        uses: aqua-github-actions/ga-aqua-login@v1.0.1
        env:
          AQUA_USERNAME: ${{ secrets.AQUA_USERNAME }}
          AQUA_PASSWORD: ${{ secrets.AQUA_PASSWORD }}
      - name: set transition to 'new'
        uses: ./
        env:
          NODE_DEBUG: http, net, stream
        with:
          aqua-token: ${{ steps.login.outputs.token }}
          defect: DF001268
          transition: new
      - name: to 'solved'
        uses: ./
        env:
          NODE_DEBUG: http, net, stream
        with:
          aqua-token: ${{ steps.login.outputs.token }}
          defect: DF001268
          transition: solved
      - name: to 'in processing'
        uses: ./
        env:
          NODE_DEBUG: http, net, stream
        with:
          aqua-token: ${{ steps.login.outputs.token }}
          defect: DF001268
          transition: in processing
      - name: to 'reopened'
        uses: ./
        env:
          NODE_DEBUG: http, net, stream
        with:
          aqua-token: ${{ steps.login.outputs.token }}
          defect: DF001268
          transition: reopened
      - name: to 'closed'
        uses: ./
        env:
          NODE_DEBUG: http, net, stream
        with:
          aqua-token: ${{ steps.login.outputs.token }}
          defect: DF001268
          transition: closed
      - name: to 'paused'
        uses: ./
        env:
          NODE_DEBUG: http, net, stream
        with:
          aqua-token: ${{ steps.login.outputs.token }}
          defect: DF001268
          transition: paused
      - name: logout to aqua saas instance
        uses: aqua-github-actions/ga-aqua-logout@v1.0.0
        with:
          aqua-token: ${{ steps.login.outputs.token }}

